#!/usr/bin/env python3
"""
Script to identify and review AI-generated corrections in exercise files.
"""

import os
import re
import json

def read_file(filepath):
    """Read a file and return its contents."""
    with open(filepath, 'r', encoding='utf-8') as f:
        return f.read()

def extract_correction(content):
    """Extract the correction block from LaTeX content."""
    match = re.search(r'\\correction\{(.*?)\n\}', content, re.DOTALL)
    if match:
        return match.group(1)
    return None

def has_ai_marker(correction):
    """Check if correction contains AI generation markers."""
    if not correction:
        return False
    ai_markers = [
        'Generated by AI',
        'Correction générée par IA',
        'generated with AI',
        'générée par IA'
    ]
    return any(marker in correction for marker in ai_markers)

def analyze_exercises(src_dir, exercise_ids):
    """Analyze the specified exercises and return detailed information."""
    results = []

    for ex_id in exercise_ids:
        tex_path = os.path.join(src_dir, f"{ex_id}.tex")
        json_path = os.path.join(src_dir, f"{ex_id}.json")

        if not os.path.exists(tex_path):
            print(f"Warning: {tex_path} not found")
            continue

        # Read files
        tex_content = read_file(tex_path)
        correction = extract_correction(tex_content)

        # Read metadata
        metadata = {}
        if os.path.exists(json_path):
            with open(json_path, 'r', encoding='utf-8') as f:
                metadata = json.load(f)

        # Analyze correction
        has_ai = has_ai_marker(correction) if correction else False
        correction_length = len(correction.strip()) if correction else 0

        results.append({
            'id': ex_id,
            'niveau': metadata.get('niveau', 'unknown'),
            'theme': metadata.get('theme', 'unknown'),
            'topic': metadata.get('topic', 'unknown'),
            'piments': metadata.get('piments', 0),
            'has_ai_marker': has_ai,
            'correction_length': correction_length,
            'has_correction': bool(correction and correction.strip())
        })

    return results

def main():
    src_dir = "/home/nathan/Documents/enseignement/documentsLaTeX/enseignementTex/src_exos"

    exercise_ids = [
        '5fh1d', 'k481d', 'zuran', 'ka15h', '3e21y', 'fydq8', 'fxwf8', '6qaau',
        'qjpyj', 'f6wvk', 'exev8', 'eunpj', '5xfze', 'p7rny', 'jhavr', 'p3dkt',
        'ju1wa', 'j8hdu', 'b52kh', '74119', 'nsmhh', '5yxjm', 'js1pf', '8csxg',
        'fadzs', 'h6e65', 'rqexr', 'tnh2w', 'sgvqw', 'ddm8s', 'fvs2g', 'ur87x',
        '1a2ea', '695hr', 'dgxhd', 'b7f66', '4sun4', 'qkz3z', 'rqd6n', 'pbjwq',
        'hhksj', 'areny', 'ahx6s', 'r92kg', 'auu1q', '3exms', '4pmjf', 'b6sz1',
        '5mcny', 'bgaa8', 'hrm6y', 'aef2y', 'pju6j', 'ivj7s', 'sgsgp'
    ]

    print(f"Analyzing {len(exercise_ids)} exercises...\n")
    results = analyze_exercises(src_dir, exercise_ids)

    # Print summary
    print("=" * 80)
    print("SUMMARY OF AI-GENERATED CORRECTIONS")
    print("=" * 80)
    print(f"\nTotal exercises analyzed: {len(results)}")

    # Group by niveau
    by_niveau = {}
    for r in results:
        niveau = r['niveau']
        if niveau not in by_niveau:
            by_niveau[niveau] = []
        by_niveau[niveau].append(r)

    print("\nBy niveau:")
    for niveau in sorted(by_niveau.keys()):
        print(f"  {niveau}: {len(by_niveau[niveau])} exercises")

    # Group by theme
    by_theme = {}
    for r in results:
        theme = r['theme']
        if theme not in by_theme:
            by_theme[theme] = []
        by_theme[theme].append(r)

    print("\nBy theme:")
    for theme in sorted(by_theme.keys()):
        print(f"  {theme}: {len(by_theme[theme])} exercises")

    # Detailed list
    print("\n" + "=" * 80)
    print("DETAILED LIST")
    print("=" * 80)
    print(f"\n{'ID':<8} {'Niveau':<8} {'Theme':<15} {'Topic':<25} {'Pim':<4} {'Length':<7}")
    print("-" * 80)
    for r in sorted(results, key=lambda x: (x['niveau'], x['theme'])):
        print(f"{r['id']:<8} {r['niveau']:<8} {r['theme']:<15} {r['topic'][:24]:<25} {r['piments']:<4} {r['correction_length']:<7}")

if __name__ == '__main__':
    main()
